import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import"./style.css";
import { ThemeProvider } from "next-themes"; //Ce composant enveloppe son contenu dans NextThemeProvider,permettant ainsi l'utilisation des fonctionnalités de next-themes comme le changement de thème.
import clsx from "clsx";// pour conditionner les classes CSS.
import Header from "@/src/feature/Header";
import Footer from "@/src/feature/Footer";

const inter = Inter({ subsets: ["latin"] }); //Inter de next/font/google pour charger la police Google Inter.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={clsx(inter.className ,'bg-background-100 h-full')} >
       <ThemeProvider attribute="class" defaultTheme="system" enableSystem> 
        <div className="flex flex-col h-full">
          <Header/>
            <div className="flex-1 max-w-lg py-14 m-auto w-full">{children}</div>
           <Footer/>  
        </div>
      </ThemeProvider> 
      {/* <div className="bg-red-700"> next</div> */}

      {/* Les attributs attribute, defaultTheme et enableSystem configurent le comportement du thème. */}
      {/* PERMET DE MODIFIER LE CSS AVEC BUTTONVARIANT, Applique des classes CSS en utilisant clsx pour ajouter la classe de la police et une classe de fond (bg-background). */}
      {/* Les metadata définissent les métadonnées de la page, telles que le titre et la description. */}
        {/* attribute="class" : Utilise des classes pour gérer les thèmes.
       defaultTheme="system" : Par défaut, utilise le thème système.
       enableSystem : Active la détection des préférences système. */}
        </body>
    </html>
  );
}
